### ISSUE TITLE
Add meta-documentation

### ISSUE THREAD

**Issue by MarekSuchanek** [OntoUML/OntoUML#36]
Document how this documentation works:

- [ ] Rendering of information from `meta.yml` files (@MarekSuchanek)
- [ ] ReadTheDocs, Sphinx, trigger (@MarekSuchanek)
- [ ] OpenPonk, updatingIndex etc. (@belohma2)
